# Generated by Django 5.1.9 on 2025-06-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0044_bookmark_latest_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="display_reader_mode_bookmark_action",
            field=models.BooleanField(default=False),
        ),
    ]
