# Generated by Django 5.1.9 on 2025-06-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0045_userprofile_display_reader_mode_bookmark_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="open_snapshot_by_default",
            field=models.BooleanField(default=False),
        ),
    ]
