# Generated by Django 5.1.9 on 2025-06-08 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0046_userprofile_open_snapshot_by_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="latest_snapshot_body",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="latest_snapshot_body",
                to="bookmarks.bookmarkasset",
            ),
        ),
    ]
